### ISSUE TITLE
Crash sometimes while opening any video file - unpredictable

### ISSUE THREAD

**Issue by Growlertiger** [RandomEngy/VidCoder#2]
Version: Latest release 1.5.32, also latest betas, 2.11 and 2.12
File loaded: Any video file - these are .mkv files
System: Win 10 Pro 64 bit 12GB memory, lots of disk space, never goes wrong or crashes.
The program works perfectly. It never crashes when encoding.
But when I do the simple action of opening a video file it sometimes, randomly, crashes in the middle of opening it. For example if I try to open six files in a row it might crash on the first one, or the third one or the sixth one or none of them. If I try again it may work that time or it may not. So it isn't any specific file.
If I can help by proving any more info please let me know. Here is the event log for a crash with the latest beta:
Faulting application name: VidCoder.exe, version: 2.12.0.0, time stamp: 0x565d0e38
Faulting module name: hb.dll, version: 0.0.0.0, time stamp: 0x56396416
Exception code: 0xc0000005
Fault offset: 0x000000000012751b
Faulting process ID: 0x2cf4
Faulting application start time: 0x01d12db4acf49078
Faulting application path: C:\Program Files\VidCoder-Beta\VidCoder.exe
Faulting module path: C:\Program Files\VidCoder-Beta\hb.dll
Report ID: 4d0d1f73-d89b-4052-b0e7-a8a9f30a5462
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Growlertiger** [comment]
I now think it possible that this was caused by a hardware problem brought on by overheating. I have reduced CPU speed to keep temperatres below 80 and today the problem is not happening.
I may be wrong about the cause as it still seems odd that the crashes would only ever happen when opening a file and never at any other time such as when encoding it.

**Comment by batjac7** [comment]
Mine too crashes on loading files. MKV files. Windows 10, 64 bit. Not lacking on hard drive space nor memory. No issues nor history with any other program crashing. When the program crashes all I do is reload the program press control-o and try to re-open the file. Current batch is 3 filures in the first 13 files. I do not have success loading a directory nor group of files (95% failure rate when loading multiple files). 
Also, it has a 1 in 5 to 1 in 7 success run rate. I have only used the normal preset. I've always been able to try again or again or again and sooner or later, successfully transform the files. Once or twice given up, deleted the file and gone on with life. 
I am grateful to be able to do this at all with these issues. Thanks for the program. I am you fan.

**Comment by RandomEngy** [comment]
This is one of those that I've gotten reports of but have never been able to get to happen myself. Is this with bulk loading of files or can it happen when opening an individual file as well?

**Comment by Growlertiger** [comment]
I could open the program, then open one single mkv file, and it might crash.
It definitely doesn't depend on the file, the same file will load or crash depending on good luck.
Yesterday I loaded dozens of .mp4 files and it never crashed.
I suggest you try to load a whole lot of mkv files one after another.

I just tried to make it crash. I loaded about 20 mkv files and it worked perfectly - there is no way that would have happened two days ago, I would not be that lucky. So that makes me think my idea that for some strange reason the load process likes to crash if the hardware is struggling might be true.
batjac7 - is your system overclocked or very hot? If so, try turning off overclocking and then try. By reducing my overclocking I now can't make it crash.

I don't even know how to load more than one file at once, I thought you had to load a file, add to queue, load file, add to queue etc. If there is a way to load lots of files at once please tell me!

**Comment by batjac7** [comment]
Can happen opening individual files. The first thing after selecting a file is scanning source and that hangs at a couple different points than crashes. That said I tried it tonight when I got back and for some reason it will not crash either. This morning I had to restart several times.

**Comment by batjac7** [comment]
And do not have a problem. Not one crash while loading in the last day.

**Comment by iamjaydear** [comment]
When you first open VidCoder, to the right of "Choose video source" and just above the "Destination" bar it says "(Or drag video files or folders here)", which you do from Windows Explorer. Quite often, but not always, for years now VidCoder may crash during the scanning phase.

**Comment by Growlertiger** [comment]
iamjaydear - thank you so much for explaining that if you drag and drop you can load many files at once.
It would be well worth putting that information in the documentation - I had looked everywhere.

My theory now is that some files are more likely than others to make it crash when they are scanned, but it is so random that it is impossible to prove. Surely the crash information in Event Viewer I gave above helps find the answer?

**Comment by iamjaydear** [comment]
My pleasure. The multiple drag and drop thing works in many programs that can handle more than one file at a time. You can even drop a file or files into that area whilst there is an encode running and they just add onto the waiting list! 
I've been using VidCoder for a couple of years and the crashing has been part of it the whole time. It is very intermittent, sometimes I go for months without it happening and then it'll do it several times in one day. RandomEngy knows its real - must be frustrating.

**Comment by arrisnyte** [comment]
I am having the same issue as well. Can open files routinely with no problem, any time I attempt to open a 10-bit mkv, Vidcoder crashes and closes. Handbrake can open the file, but has issues encoding it correctly (or at all).

**Comment by RandomEngy** [comment]
Give 2.39 Beta a try. I've moved batch scans to a worker process; it might be more stable in this scenario now.

**Comment by Growlertiger** [comment]
I have just tried loading into the queue a huge number of files across many sources and many folders, and it didn't crash. This gives me confidence that the problem is solved. Thanks and well done.

A new very minor issue, having put all those files in the queue, I tried to delete them all. I selected them all, right-click and Delete. It only deletes some at a time, it took many goes to get rid of them all.

**Comment by batjac7** [comment]
I got it to crash. I grabbed 3 folders of smallish 80M-180M mkv shows to
convert. On the last I got a error scanning (see below) I had not seen
before and four files would not load in the queue. I repicked the four. On
the second go-around one would still not load and than VidCoder crashed. I
restarted, reloaded the last file and just hit convert. I won't know how it
does until I get home from work.

[image: Inline image 1]

One thing I did lately. I made 4 different presets and identified video
quality. I am slowly learning what to choose between small 80M videos and
7G quality movies. Assuming that there is no excuse to have a larger file
size than the source. I made presets for quality identified (Norm 20, Good
18, Better 16, Great 14). I -assume- that if I leave sound at 5.1 for all
the mixdown conversion will be as good as the source (?).
